# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Everywherechat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod ‘Firebase/Database’
pod ‘Firebase/Auth’
pod ‘Firebase/Storage’

  # Pods for Everywherechat

  target 'EverywherechatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EverywherechatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
